---
kind: pipeline
name: integration-tests-stable20

clone:
  depth: 1

steps:
  - name: integration-tests-stable20
    image: ghcr.io/nextcloud/continuous-integration-user_saml_shibboleth-php7.3:latest
    environment:
      CORE_BRANCH: stable20
    commands:
      - yum -y install rh-php73-php-intl # temporary – NC20 has an issue when intl is not enabled
      - /start.sh
      - /wait-for-services.sh
      - rm -rf /var/www/html
      - cd /var/www/
      - git clone --depth 1 -b $CORE_BRANCH https://github.com/nextcloud/server html
      - cd /var/www/html && git submodule update --init
      # use local clone
      - cp -r /drone/src /var/www/html/apps/user_saml
      - scl enable rh-php73 "bash -c 'php /var/www/html/occ maintenance:install --database sqlite --admin-pass password'"
      - scl enable rh-php73 "bash -c 'php /var/www/html/occ app:enable user_saml'"
      - chown -R apache:apache /var/www/html/
      - scl enable rh-php73 "bash -c 'cd /var/www/html/apps/user_saml/tests/integration && vendor/bin/behat'"

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

type: docker
---
kind: signature
hmac: c1f937596587c608b6d7b7cce152d8a539cf5fe670fa6f260063cb005e27a4b2
